remote_theme: broccolini/swiss
theme_color: red
title: Max Triano
description: >
  Computer science student, runner, geek. I might write stuff here sometimes.
  
social_link: twitter
social_username: maxtriano
