#remote_theme: broccolini/swiss
#theme_color: black
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "sunrise"
title: Max Triano
description: >
  Hi!
  
plugins:
    - jekyll-include-cache
    
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
